apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-service-config
  namespace: toogle-master
data:
  PORT: "8005"
  AWS_REGION: "us-east-1"
  # Nome sincronizado com o Terraform (module.database -> ToggleMasterAnalytics)
  AWS_DYNAMODB_TABLE: "ToggleMasterAnalytics"
